<template>
    <my-table :table-data="myData" :columns="myColumns" :table-width="1200" :screen-height="600"></my-table>
</template>

<script>
import myTable from './package/multi-level-table/MultiLevelTable.vue';
export default {
    components:{
        myTable
    },
    data() {
        return {
            myData: [
                {
                    G1: '单位1',
                    ROUTE_NAME: '路段1',
                    LINE_CODE: '编号1',
                    LINE_ALLNAME: '路线1',
                    START_STAKE: '起点1',
                    END_STAKE: '终点1',
                    LINE_DIRECT: '方向1',
                    PAVEMENT_TYPE: '类型1',
                    ROUTE_LENGTH: '长度1',
                    MQI: 'MQI1',
                    PQI: 'PQI1',
                    PCI: 'PCI1',
                    RQI: 'RQI1',
                    RDI: 'RDI1',
                    SRI: 'SRI1',
                    PBI: 'PBI1',
                    Remark: '备注1',
                },
                {
                    G1: '单位1',
                    ROUTE_NAME: '路段1',
                    LINE_CODE: '编号1',
                    LINE_ALLNAME: '路线1',
                    START_STAKE: '起点1',
                    END_STAKE: '终点1',
                    LINE_DIRECT: '方向1',
                    PAVEMENT_TYPE: '类型1',
                    ROUTE_LENGTH: '长度1',
                    MQI: 'MQI1',
                    PQI: 'PQI1',
                    PCI: 'PCI1',
                    RQI: 'RQI1',
                    RDI: 'RDI1',
                    SRI: 'SRI1',
                    PBI: 'PBI1',
                    Remark: '备注1',
                },
                {
                    G1: '单位1',
                    ROUTE_NAME: '路段1',
                    LINE_CODE: '编号1',
                    LINE_ALLNAME: '路线1',
                    START_STAKE: '起点1',
                    END_STAKE: '终点1',
                    LINE_DIRECT: '方向1',
                    PAVEMENT_TYPE: '类型1',
                    ROUTE_LENGTH: '长度1',
                    MQI: 'MQI1',
                    PQI: 'PQI1',
                    PCI: 'PCI1',
                    RQI: 'RQI1',
                    RDI: 'RDI1',
                    SRI: 'SRI1',
                    PBI: 'PBI1',
                    Remark: '备注1',
                },
                {
                    G1: '单位1',
                    ROUTE_NAME: '路段1',
                    LINE_CODE: '编号1',
                    LINE_ALLNAME: '路线1',
                    START_STAKE: '起点1',
                    END_STAKE: '终点1',
                    LINE_DIRECT: '方向1',
                    PAVEMENT_TYPE: '类型1',
                    ROUTE_LENGTH: '长度1',
                    MQI: 'MQI1',
                    PQI: 'PQI1',
                    PCI: 'PCI1',
                    RQI: 'RQI1',
                    RDI: 'RDI1',
                    SRI: 'SRI1',
                    PBI: 'PBI1',
                    Remark: '备注1',
                },
                {
                    G1: '单位1',
                    ROUTE_NAME: '路段1',
                    LINE_CODE: '编号1',
                    LINE_ALLNAME: '路线1',
                    START_STAKE: '起点1',
                    END_STAKE: '终点1',
                    LINE_DIRECT: '方向1',
                    PAVEMENT_TYPE: '类型1',
                    ROUTE_LENGTH: '长度1',
                    MQI: 'MQI1',
                    PQI: 'PQI1',
                    PCI: 'PCI1',
                    RQI: 'RQI1',
                    RDI: 'RDI1',
                    SRI: 'SRI1',
                    PBI: 'PBI1',
                    Remark: '备注1',
                },
                {
                    G1: '单位1',
                    ROUTE_NAME: '路段1',
                    LINE_CODE: '编号1',
                    LINE_ALLNAME: '路线1',
                    START_STAKE: '起点1',
                    END_STAKE: '终点1',
                    LINE_DIRECT: '方向1',
                    PAVEMENT_TYPE: '类型1',
                    ROUTE_LENGTH: '长度1',
                    MQI: 'MQI1',
                    PQI: 'PQI1',
                    PCI: 'PCI1',
                    RQI: 'RQI1',
                    RDI: 'RDI1',
                    SRI: 'SRI1',
                    PBI: 'PBI1',
                    Remark: '备注1',
                },
                {
                    G1: '单位1',
                    ROUTE_NAME: '路段1',
                    LINE_CODE: '编号1',
                    LINE_ALLNAME: '路线1',
                    START_STAKE: '起点1',
                    END_STAKE: '终点1',
                    LINE_DIRECT: '方向1',
                    PAVEMENT_TYPE: '类型1',
                    ROUTE_LENGTH: '长度1',
                    MQI: 'MQI1',
                    PQI: 'PQI1',
                    PCI: 'PCI1',
                    RQI: 'RQI1',
                    RDI: 'RDI1',
                    SRI: 'SRI1',
                    PBI: 'PBI1',
                    Remark: '备注1',
                },
                {
                    G1: '单位1',
                    ROUTE_NAME: '路段1',
                    LINE_CODE: '编号1',
                    LINE_ALLNAME: '路线1',
                    START_STAKE: '起点1',
                    END_STAKE: '终点1',
                    LINE_DIRECT: '方向1',
                    PAVEMENT_TYPE: '类型1',
                    ROUTE_LENGTH: '长度1',
                    MQI: 'MQI1',
                    PQI: 'PQI1',
                    PCI: 'PCI1',
                    RQI: 'RQI1',
                    RDI: 'RDI1',
                    SRI: 'SRI1',
                    PBI: 'PBI1',
                    Remark: '备注1',
                },
                {
                    G1: '单位1',
                    ROUTE_NAME: '路段1',
                    LINE_CODE: '编号1',
                    LINE_ALLNAME: '路线1',
                    START_STAKE: '起点1',
                    END_STAKE: '终点1',
                    LINE_DIRECT: '方向1',
                    PAVEMENT_TYPE: '类型1',
                    ROUTE_LENGTH: '长度1',
                    MQI: 'MQI1',
                    PQI: 'PQI1',
                    PCI: 'PCI1',
                    RQI: 'RQI1',
                    RDI: 'RDI1',
                    SRI: 'SRI1',
                    PBI: 'PBI1',
                    Remark: '备注1',
                },
                {
                    G1: '单位1',
                    ROUTE_NAME: '路段1',
                    LINE_CODE: '编号1',
                    LINE_ALLNAME: '路线1',
                    START_STAKE: '起点1',
                    END_STAKE: '终点1',
                    LINE_DIRECT: '方向1',
                    PAVEMENT_TYPE: '类型1',
                    ROUTE_LENGTH: '长度1',
                    MQI: 'MQI1',
                    PQI: 'PQI1',
                    PCI: 'PCI1',
                    RQI: 'RQI1',
                    RDI: 'RDI1',
                    SRI: 'SRI1',
                    PBI: 'PBI1',
                    Remark: '备注1',
                },
                {
                    G1: '单位1',
                    ROUTE_NAME: '路段1',
                    LINE_CODE: '编号1',
                    LINE_ALLNAME: '路线1',
                    START_STAKE: '起点1',
                    END_STAKE: '终点1',
                    LINE_DIRECT: '方向1',
                    PAVEMENT_TYPE: '类型1',
                    ROUTE_LENGTH: '长度1',
                    MQI: 'MQI1',
                    PQI: 'PQI1',
                    PCI: 'PCI1',
                    RQI: 'RQI1',
                    RDI: 'RDI1',
                    SRI: 'SRI1',
                    PBI: 'PBI1',
                    Remark: '备注1',
                },
                {
                    G1: '单位1',
                    ROUTE_NAME: '路段1',
                    LINE_CODE: '编号1',
                    LINE_ALLNAME: '路线1',
                    START_STAKE: '起点1',
                    END_STAKE: '终点1',
                    LINE_DIRECT: '方向1',
                    PAVEMENT_TYPE: '类型1',
                    ROUTE_LENGTH: '长度1',
                    MQI: 'MQI1',
                    PQI: 'PQI1',
                    PCI: 'PCI1',
                    RQI: 'RQI1',
                    RDI: 'RDI1',
                    SRI: 'SRI1',
                    PBI: 'PBI1',
                    Remark: '备注1',
                },
                {
                    G1: '单位1',
                    ROUTE_NAME: '路段1',
                    LINE_CODE: '编号1',
                    LINE_ALLNAME: '路线1',
                    START_STAKE: '起点1',
                    END_STAKE: '终点1',
                    LINE_DIRECT: '方向1',
                    PAVEMENT_TYPE: '类型1',
                    ROUTE_LENGTH: '长度1',
                    MQI: 'MQI1',
                    PQI: 'PQI1',
                    PCI: 'PCI1',
                    RQI: 'RQI1',
                    RDI: 'RDI1',
                    SRI: 'SRI1',
                    PBI: 'PBI1',
                    Remark: '备注1',
                },
                {
                    G1: '单位1',
                    ROUTE_NAME: '路段1',
                    LINE_CODE: '编号1',
                    LINE_ALLNAME: '路线1',
                    START_STAKE: '起点1',
                    END_STAKE: '终点1',
                    LINE_DIRECT: '方向1',
                    PAVEMENT_TYPE: '类型1',
                    ROUTE_LENGTH: '长度1',
                    MQI: 'MQI1',
                    PQI: 'PQI1',
                    PCI: 'PCI1',
                    RQI: 'RQI1',
                    RDI: 'RDI1',
                    SRI: 'SRI1',
                    PBI: 'PBI1',
                    Remark: '备注1',
                },
                {
                    G1: '单位1',
                    ROUTE_NAME: '路段1',
                    LINE_CODE: '编号1',
                    LINE_ALLNAME: '路线1',
                    START_STAKE: '起点1',
                    END_STAKE: '终点1',
                    LINE_DIRECT: '方向1',
                    PAVEMENT_TYPE: '类型1',
                    ROUTE_LENGTH: '长度1',
                    MQI: 'MQI1',
                    PQI: 'PQI1',
                    PCI: 'PCI1',
                    RQI: 'RQI1',
                    RDI: 'RDI1',
                    SRI: 'SRI1',
                    PBI: 'PBI1',
                    Remark: '备注1',
                },
                {
                    G1: '单位1',
                    ROUTE_NAME: '路段1',
                    LINE_CODE: '编号1',
                    LINE_ALLNAME: '路线1',
                    START_STAKE: '起点1',
                    END_STAKE: '终点1',
                    LINE_DIRECT: '方向1',
                    PAVEMENT_TYPE: '类型1',
                    ROUTE_LENGTH: '长度1',
                    MQI: 'MQI1',
                    PQI: 'PQI1',
                    PCI: 'PCI1',
                    RQI: 'RQI1',
                    RDI: 'RDI1',
                    SRI: 'SRI1',
                    PBI: 'PBI1',
                    Remark: '备注1',
                },

                // ...更多数据
            ],
            myColumns: [
                { type: 'index' },
                { prop: 'G1', label: '运营(管养)单位', minWidth: '100' , sortable: true},
                { prop: 'ROUTE_NAME', label: '路段名称', minWidth: '275' , sortable: false},
                { prop: 'LINE_CODE', label: '路线编号', minWidth: '81' },
                { prop: 'LINE_ALLNAME', label: '路线名称', minWidth: '208' },
                { prop: 'START_STAKE', label: '起点桩号', minWidth: '84' },
                { prop: 'END_STAKE', label: '终点桩号', minWidth: '84' },
                { prop: 'LINE_DIRECT', label: '检测方向(上/下行)', minWidth: '200' },
                { prop: 'PAVEMENT_TYPE', label: '路面类型', minWidth: '160' },
                { prop: 'ROUTE_LENGTH', label: '路段长度/米', minWidth: '70' },
                { label: '评定结果', minWidth: '60',
                    subColumns: [
                        { prop: 'MQI', label: 'MQI', minWidth: '60' },
                        { prop: 'PQI', label: '路面PQI', minWidth: '60' },
                        { label: '评定结果', minWidth: '60',
                            subColumns: [
                                { prop: 'PCI', label: 'PCI', minWidth: '60' },
                                { prop: 'RQI', label: 'RQI', minWidth: '60' },
                                { prop: 'RDI', label: 'RDI', minWidth: '60' },
                                { prop: 'SRI', label: 'SRI', minWidth: '60' },
                                { prop: 'PBI', label: 'PBI', minWidth: '60' },
                                // 你可以在此添加更多层次的子列
                                { label: '评定结果', minWidth: '60',
                                    subColumns: [
                                        { prop: 'PCI', label: 'PCI', minWidth: '60' },
                                        { prop: 'RQI', label: 'RQI', minWidth: '60' },
                                        { prop: 'RDI', label: 'RDI', minWidth: '60' },
                                        { prop: 'SRI', label: 'SRI', minWidth: '60' },
                                        { prop: 'PBI', label: 'PBI', minWidth: '60' },
                                        // 你可以在此添加更多层次的子列
                                        { label: '评定结果', minWidth: '60',
                                            subColumns: [
                                                { prop: 'PCI', label: 'PCI', minWidth: '60' },
                                                { prop: 'RQI', label: 'RQI', minWidth: '60' },
                                                { prop: 'RDI', label: 'RDI', minWidth: '60' },
                                                { prop: 'SRI', label: 'SRI', minWidth: '60' },
                                                { prop: 'PBI', label: 'PBI', minWidth: '60' },
                                                // 你可以在此添加更多层次的子列
                                            ]
                                        },
                                    ]
                                },
                            ]
                        },
                    ]
                },
                { prop: 'Remark', label: '备注', minWidth: '120' },
            ]
        }
    }
}
</script>
